[default-profile]
sh_client_id = "sh-792ab2c7-0d03-4a90-b6d4-416779d61820"
sh_client_secret = "zs2HqVN1UCRNx3P9dZhIlLBDTxOCQ4V4"
sh_base_url = 'https://sh.dataspace.copernicus.eu'
sh_token_url = 'https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token'